### ISSUE TITLE
Create button/link to log out

### ISSUE THREAD

**Issue by rhoitink** [euismod2336/bolt-googlelogin#5]
You're now only able to sign in, but not sign out. On public computers, this might be a wanted feature

**Comment by euismod2336** [comment]
I would assume logging out of Google would solve this. Since it works in conjunction with your session with gmail. There is an option to revoke access, but then users will have to grant access again on a later date.

**Comment by rhoitink** [comment]
May be could create a route that unsets the specific sessions created by this plugin. Just like how the route is set for the OAuth Callback

**Comment by euismod2336** [comment]
To be honest, the variables shouldn't be set in the $_SESSION in first place. Since the functions return the values, it should be rewritten to use private variables which are retrieved when appropriate.

**Comment by euismod2336** [comment]
Well, this turned out to be more of a pain then i thought :)

instead of rewriting to use private variables (this would cause infinite loops) i've added a logout function which is mapped to an url.

commit: 1dd2953e387b16caab9bd30307ae2aa088a19ea6
